version: '3.8'

services:
  spring-job-config-db:
    image: postgres:latest
    container_name: spring-job-config-db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring_batch_db
    ports:
      - "5433:5432"
    networks:
      - pubmed-network

  pubmed-service:
    image: fmahmud26/pubmed-service:v2024.7.1
    container_name: pubmed-service
    ports:
      - "80:8080"
    depends_on:
      - spring-job-config-db
    networks:
      - pubmed-network

  biopython-service:
    image: fmahmud26/biopython-service:v2024.7.1
    container_name: biopython-service
    ports:
      - "5000:5000"
    networks:
      - pubmed-network

networks:
  pubmed-network:
    driver: bridge
